// Package model Code generated by generator.
package model

type User struct {
	ID          int    `db:"id" json:"id"`
	ChineseName string `db:"cn_name" json:"cn_name"`
	Name        string `db:"name" json:"name"`
}

const SchemaUser = `
		CREATE TABLE user ( 
			id	SERIAL PRIMARY KEY, 
			cn_name	text, 
			name	text, 
); 
`
