// Code generated by generator.
package model

import (
	model "GenFromStruct/sampleData/mypack/model"
	"context"
	"fmt"
	squirrel "github.com/Masterminds/squirrel"
)

func InsertProject(ctx context.Context, runner squirrel.BaseRunner, projectPtr model.ProjectPtr) error {
	_, err := squirrel.Insert("project").SetMap(projectPtr.ToDbMap()).RunWith(runner).PlaceholderFormat(squirrel.Dollar).ExecContext(ctx)
	return err
}
func UpdateProject(ctx context.Context, runner squirrel.BaseRunner, projectPtr model.ProjectPtr) error {
	res, err := squirrel.Update("project").Where(squirrel.Eq{"project_id": *(projectPtr.ID)}).SetMap(projectPtr.ToDbMap()).RunWith(runner).PlaceholderFormat(squirrel.Dollar).ExecContext(ctx)
	if err != nil {
		return err
	}
	rowsAffected, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if rowsAffected != 1 {
		return fmt.Errorf("rows affected %d rows, but expected 1", rowsAffected)
	}
	return err
}
