// Code generated by generator.
package model

import (
	model "GenFromStruct/sampleData/mypack/model"
	"context"
	squirrel "github.com/Masterminds/squirrel"
)

func InsertProject(ctx context.Context, runner squirrel.BaseRunner, project model.Project) error {
	return nil
}
