package generator

import (
	"GenFromStruct/GenFromPackage/model"
	"GenFromStruct/utils"
	. "github.com/dave/jennifer/jen"
	"os"
	"path/filepath"
)

func GenerateDbOps(si model.StructInfo) error {
	modelPath := filepath.Join(si.FilePath, "dbOps")
	modelFileName := filepath.Join(modelPath, si.StructName+".go")

	// make path if not exist
	_, err := os.Stat(modelPath)
	if os.IsNotExist(err) {
		os.Mkdir(modelPath, os.ModePerm)
	}

	// create model file
	f := NewFile("model")
	f.PackageComment("Code generated by generator.")

	// Generate ToDbMap function
	// 1. Collect code in toMap() block
	var InsertOpsBlock []Code

	// 2. Build "m := make(map[string]interface{})"
	//InsertOpsBlock = append(InsertOpsBlock, Id("m").Op(":=").Make(Map(String()).Interface()))

	//code := Id("").Op(":=").Qual("github.com/jmoiron/sqlx", "Insert").
	//	Call(Id(utils.Camel2camel(si.StructName))).Id
	//	Call(Id("runner"))
	//
	//InsertOpsBlock = append(InsertOpsBlock, code)

	// 4. Build return statement
	InsertOpsBlock = append(InsertOpsBlock, Return(Nil()))

	// 5. Build toMap method
	f.Func().Id("Insert"+si.StructName).
		Params(Id("ctx").Qual("context", "Context"),
			Id("runner").Qual("github.com/Masterminds/squirrel", "BaseRunner"),
			Id(utils.Camel2camel(si.StructName)).Qual(si.PackagePath+"/model", si.StructName),
		).Error().Block(
		InsertOpsBlock...,
	)

	// Write generated file
	return f.Save(modelFileName)
}
